#!/usr/bin/env bash
# Render (or remove) Grafana's Telegram contact point + notification policy.
#
# Grafana's file provisioning has no conditional/env-substitution support,
# so a contact point that embeds a secret bot token can't just be a static
# file in the repo. Instead: when both TELEGRAM_BOT_TOKEN and
# TELEGRAM_CHAT_ID are set (normally sourced from .env by deploy.sh), this
# writes contact-points.yaml + policies.yaml into the alerting provisioning
# directory, routing every alert to Telegram. When either is unset, it
# removes those two files (if present) so Grafana falls back to its
# built-in default email contact point — the dashboard and alert rules work
# either way, only where the notification goes changes.
#
# Usage: deploy/render-telegram-alerting.sh <provisioning/alerting dir>
# Reads TELEGRAM_BOT_TOKEN / TELEGRAM_CHAT_ID from the environment.
set -euo pipefail

dir="${1:?usage: render-telegram-alerting.sh <provisioning/alerting dir>}"
contact_file="$dir/contact-points.yaml"
policy_file="$dir/policies.yaml"

if [ -n "${TELEGRAM_BOT_TOKEN:-}" ] && [ -n "${TELEGRAM_CHAT_ID:-}" ]; then
	mkdir -p "$dir"
	cat >"$contact_file" <<EOF
# Generated by deploy/render-telegram-alerting.sh from TELEGRAM_BOT_TOKEN /
# TELEGRAM_CHAT_ID in .env. Not meant to be hand-edited or committed.
apiVersion: 1

contactPoints:
  - orgId: 1
    name: telegram
    receivers:
      - uid: tolerance-telegram
        type: telegram
        settings:
          bottoken: "${TELEGRAM_BOT_TOKEN}"
          chatid: "${TELEGRAM_CHAT_ID}"
          parse_mode: None
EOF
	cat >"$policy_file" <<EOF
# Generated by deploy/render-telegram-alerting.sh. Not meant to be
# hand-edited or committed.
apiVersion: 1

policies:
  - orgId: 1
    receiver: telegram
    group_by: ["alertname"]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
EOF
	echo "render-telegram-alerting: wrote Telegram contact point + policy to $dir"
else
	rm -f "$contact_file" "$policy_file"
	echo "render-telegram-alerting: TELEGRAM_BOT_TOKEN/TELEGRAM_CHAT_ID not both set, using Grafana's default email contact point"
fi
